CC := gcc -std=c17

CFLAGS := -Wall -Werror -Wextra -I./include

SRCS := $(wildcard src/*.c)
OBJS := $(SRCS:.c=.o)
TARGET := my_app

all: $(TARGET)

$(TARGET): $(OBJS)
	$(CC) $(OBJS) -o $(TARGET)
	rm -f $(OBJS)

# Шаблонное правило
%.o : %.c
	$(CC) -c $(CFLAGS) $< -o $@

clean:
	rm -f $(OBJS) $(TARGET)
