all: clean build

build:
	@mkdir -p build
	@gcc part2.c -o build/part2.out
	@echo "Part2 - compilled in build"
	@gcc part3.c -o build/part3.out	
	@echo "Part3 - compilled in build"

clean:
	@rm -rf build
